// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ListenAndRepeat
{
	public partial class AddWordController : UITableViewController
	{
		public WordsModel TheWordsModel { get; set; }

		public AddWordController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			TableView.Source = new SearchTableSource(this);
			mSearchBar = TableView.TableHeaderView as UISearchBar;

			mSearchBar.Placeholder = "Enter Search Word";
			mSearchBar.SizeToFit();
			mSearchBar.AutocorrectionType = UITextAutocorrectionType.Yes;
			mSearchBar.AutocapitalizationType = UITextAutocapitalizationType.None;
			mSearchBar.SearchButtonClicked += (sender, e) => 
			{
				UIApplication.SharedApplication.NetworkActivityIndicatorVisible = true;

				var theDictSearch = new DictionarySearch(OnSearchCompleted);
				theDictSearch.Search(mSearchBar.Text);
			};
		}

		private void OnSearchCompleted(DictionaryWord theNewWord)
		{
			this.InvokeOnMainThread(delegate 
			{
				if (theNewWord != null) 
				{
					mSearchBar.ResignFirstResponder();
					TableView.ReloadData();
				} 
				else 
				{
					new UIAlertView ("", "Could not retrieve results", null, "OK").Show();
				}
				
				UIApplication.SharedApplication.NetworkActivityIndicatorVisible = false;
			});
		}

		private UISearchBar mSearchBar;
	}

	public class SearchTableSource : UITableViewSource 
	{
		string mCellIdentifier = "SearchWordCell";
		AddWordController mController;
		
		public SearchTableSource(AddWordController theController)
		{
			mController = theController;
		}
		
		public override int RowsInSection(UITableView tableview, int section)
		{
			return mController.TheWordsModel.WordList.Count;
		}

		public override UITableViewCell GetCell(UITableView tableView, MonoTouch.Foundation.NSIndexPath indexPath)
		{
			UITableViewCell cell = tableView.DequeueReusableCell(mCellIdentifier);

			cell.TextLabel.Text = mController.TheWordsModel.WordList[indexPath.Row];

			return cell;
		}

		public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			//new UIAlertView("Row Selected", tableItems[indexPath.Row], null, "OK", null).Show();
			//tableView.DeselectRow(indexPath, true); // iOS convention is to remove the highlight
		}
	}
}
