// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ListenAndRepeat.ViewModel;
using ListenAndRepeat.Util;

namespace ListenAndRepeat
{
	public partial class AddWordController : UITableViewController
	{
		public AddWordController (IntPtr handle) : base (handle)
		{
			mMainModel = ServiceContainer.Resolve<MainModel> ();
			mSuggestionModel = ServiceContainer.Resolve<SuggestionModel> ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			TableView.Source = new SearchTableSource(this);
			mSearchBar = TableView.TableHeaderView as UISearchBar;

			mSearchBar.Placeholder = "Enter Search Word";
			mSearchBar.SizeToFit();
			mSearchBar.AutocorrectionType = UITextAutocorrectionType.Yes;
			mSearchBar.AutocapitalizationType = UITextAutocapitalizationType.None;
			mSearchBar.SearchButtonClicked += (sender, e) => 
			{
				AddWord(mSearchBar.Text);
			};
			mSearchBar.TextChanged += (sender, e) => 
			{
				mSuggestionModel.NewSuggestion(mSearchBar.Text);
			};

			mSuggestionModel.SuggestionChanged += (sender, e) => 
			{
				this.InvokeOnMainThread(delegate
			    {
					TableView.ReloadData();
				});
			};

			mSearchBar.BecomeFirstResponder ();
		}

		public void AddWord (string theWord)
		{
			this.InvokeOnMainThread(delegate
			{
				mMainModel.AddWord(theWord);
				NavigationController.PopViewControllerAnimated(true);
			});
		}

		MainModel mMainModel;
		SuggestionModel mSuggestionModel;
		UISearchBar mSearchBar;
	}

	public class SearchTableSource : UITableViewSource 
	{
		AddWordController mAddWordController;
		SuggestionModel mSuggestionModel;
		string mCellIdentifier = "SearchWordCell";
				
		public SearchTableSource(AddWordController theController)
		{
			mSuggestionModel = ServiceContainer.Resolve<SuggestionModel>();
			mAddWordController = theController;
		}

		public override int RowsInSection(UITableView tableview, int section)
		{
			return mSuggestionModel.Suggestion.Count;
		}

		public override UITableViewCell GetCell(UITableView tableView, MonoTouch.Foundation.NSIndexPath indexPath)
		{
			UITableViewCell cell = tableView.DequeueReusableCell(mCellIdentifier);

			cell.TextLabel.Text = mSuggestionModel.Suggestion[indexPath.Row];

			return cell;
		}

		public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			tableView.DeselectRow(indexPath, true);
			mAddWordController.AddWord(mSuggestionModel.Suggestion[indexPath.Row]);
		}
	}
}
