// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using ListenAndRepeat.ViewModel;

namespace ListenAndRepeat
{
	public partial class WordsNavigationController : UINavigationController
	{
		public WordsNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
