// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ListenAndRepeat
{
	public partial class WordDetailController : UIViewController
	{
		public WordDetailController (IntPtr handle) : base (handle)
		{
		}
	}
}
